In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score

In [2]:
train = pd.read_csv('./_data/train.csv', index_col=0)#id를 인덱스로
test = pd.read_csv('./_data/test.csv', index_col=0)

In [6]:
y_train = train.pop('target')
y_train = y_train.to_numpy()

In [11]:
input_features = ['sex', 'cp', 'slope', 'ca', 'thal','exang','age']

In [ ]:
x_train = train.loc[:,input_features].to_numpy()

In [12]:
x_test = test.loc[:,input_features].to_numpy()

In [8]:
import tensorflow as tf
import autokeras as ak
ak_model = ak.StructuredDataClassifier(
    overwrite=True, max_trials=2, loss='binary_crossentropy'
)
ak_model.fit(x_train, y_train, epochs=80, validation_split=0.3)

Trial 2 Complete [00h 00m 02s]
val_accuracy: 0.782608687877655

Best val_accuracy So Far: 0.782608687877655
Total elapsed time: 00h 00m 07s
INFO:tensorflow:Oracle triggered exit
Epoch 1/80
5/5 [==============================] - 0s 2ms/step - loss: 0.6540 - accuracy: 0.6556
Epoch 2/80
5/5 [==============================] - 0s 1ms/step - loss: 0.5501 - accuracy: 0.7947
Epoch 3/80
5/5 [==============================] - 0s 1ms/step - loss: 0.4827 - accuracy: 0.8013
Epoch 4/80
5/5 [==============================] - 0s 1ms/step - loss: 0.4364 - accuracy: 0.8146
Epoch 5/80
5/5 [==============================] - 0s 1ms/step - loss: 0.4047 - accuracy: 0.8212
Epoch 6/80
5/5 [==============================] - 0s 1ms/step - loss: 0.3829 - accuracy: 0.8212
Epoch 7/80
5/5 [==============================] - 0s 1ms/step - loss: 0.3662 - accuracy: 0.8212
Epoch 8/80
5/5 [==============================] - 0s 2ms/step - loss: 0.3522 - accuracy: 0.8411
Epoch 9/80
5/5 [==============================] - 0s 2

In [13]:
predict_y = ak_model.predict(x_test)

5/5 [==============================] - 0s 2ms/step


In [18]:
predict_y

array([[0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],

In [19]:
submission = pd.read_csv('./_data/sample_submission.csv')

In [20]:
submission['target']=predict_y

In [21]:
submission.to_csv('./submission10.csv', index=False)

# score 0.8656716418

In [ ]:
categorical_features = ['sex', 'cp', 'slope', 'ca','exang', 'restecg', 'thal']
numeric_features = ['age', 'trestbps', 'thalach', 'fbs','oldpeak', 'chol']

thal = NULL
ca = NULL 
예측

In [26]:
train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
id                                                                         
1     53    1   2       130   197    1        0      152      0      1.2   
2     52    1   3       152   298    1        1      178      0      1.2   
3     54    1   1       192   283    0        0      195      0      0.0   
4     45    0   0       138   236    0        0      152      1      0.2   
5     35    1   1       122   192    0        1      174      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
147   50    1   2       140   233    0        1      163      0      0.6   
148   51    1   2        94   227    0        1      154      1      0.0   
149   69    1   3       160   234    1        0      131      0      0.1   
150   46    1   0       120   249    0        0      144      0      0.8   
151   63    0   1       140   195    0        1      179      0      0.0   

     slope  ca  thal  
id                    
1        0   0     2  
2        1   0     3  
3        2   1     3  
4        1   0     2  
5        2   0     2  
..     ...  ..   ...  
147      1   1     3  
148      2   1     3  
149      1   1     2  
150      2   0     3  
151      2   2     2  

[151 rows x 13 columns]

In [3]:
train_ca = pd.concat([train.drop(columns=['target']), test.drop([41,46,80,81,96])],axis=0)
train_ca

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
id                                                                         
1     53    1   2       130   197    1        0      152      0      1.2   
2     52    1   3       152   298    1        1      178      0      1.2   
3     54    1   1       192   283    0        0      195      0      0.0   
4     45    0   0       138   236    0        0      152      1      0.2   
5     35    1   1       122   192    0        1      174      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
148   64    0   0       130   303    0        1      122      0      2.0   
149   43    0   0       132   341    1        0      136      1      3.0   
150   53    1   0       123   282    0        1       95      1      2.0   
151   67    0   2       152   277    0        1      172      0      0.0   
152   43    0   2       122   213    0        1      165      0      0.2   

     slope  ca  thal  
id                    
1        0   0     2  
2        1   0     3  
3        2   1     3  
4        1   0     2  
5        2   0     2  
..     ...  ..   ...  
148      1   2     2  
149      1   0     3  
150      1   2     3  
151      2   1     2  
152      1   0     2  

[298 rows x 13 columns]

In [39]:
pred_y = test[test['ca']==4]
pred_y.pop('ca')
pred_y = pred_y.to_numpy()

In [45]:
pred_y = test[test['ca']==4]
pred_y.pop('ca')
pred_y

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
id                                                                        
41   52    1   2       138   223    0        1      169      0      0.0   
46   43    1   0       132   247    1        0      143      1      0.1   
80   58    1   1       125   220    0        1      144      0      0.4   
81   38    1   2       138   175    0        1      173      0      0.0   
96   38    1   2       138   175    0        1      173      0      0.0   

    slope  thal  
id               
41      2     2  
46      1     3  
80      1     3  
81      2     2  
96      2     2

In [46]:
x_train_ca

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
id                                                                         
1     53    1   2       130   197    1        0      152      0      1.2   
2     52    1   3       152   298    1        1      178      0      1.2   
3     54    1   1       192   283    0        0      195      0      0.0   
4     45    0   0       138   236    0        0      152      1      0.2   
5     35    1   1       122   192    0        1      174      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
148   64    0   0       130   303    0        1      122      0      2.0   
149   43    0   0       132   341    1        0      136      1      3.0   
150   53    1   0       123   282    0        1       95      1      2.0   
151   67    0   2       152   277    0        1      172      0      0.0   
152   43    0   2       122   213    0        1      165      0      0.2   

     slope  thal  
id                
1        0     2  
2        1     3  
3        2     3  
4        1     2  
5        2     2  
..     ...   ...  
148      1     2  
149      1     3  
150      1     3  
151      2     2  
152      1     2  

[298 rows x 12 columns]

In [56]:
x_train_ca.shape

(298, 12)

In [47]:
y_train_ca = train_ca.pop('ca')
y_train_ca = y_train_ca.to_numpy()
x_train_ca = train_ca.to_numpy()

In [95]:
ak_model = ak.StructuredDataClassifier(
        overwrite=True, max_trials=5, 
        loss='categorical_crossentropy', seed=32
)
ak_model.fit(x_train_ca, y_train_ca, epochs=100, validation_split=0.3)

Trial 5 Complete [00h 00m 16s]
val_accuracy: 0.6081081032752991

Best val_accuracy So Far: 0.6351351141929626
Total elapsed time: 00h 00m 39s
INFO:tensorflow:Oracle triggered exit
Epoch 1/100
10/10 [==============================] - 0s 2ms/step - loss: 1.1722 - accuracy: 0.5705
Epoch 2/100
10/10 [==============================] - 0s 2ms/step - loss: 0.9392 - accuracy: 0.6141
Epoch 3/100
10/10 [==============================] - 0s 2ms/step - loss: 0.8845 - accuracy: 0.6611
Epoch 4/100
10/10 [==============================] - 0s 2ms/step - loss: 0.8444 - accuracy: 0.6544
Epoch 5/100
10/10 [==============================] - 0s 2ms/step - loss: 0.8077 - accuracy: 0.6745
Epoch 6/100
10/10 [==============================] - 0s 2ms/step - loss: 0.7761 - accuracy: 0.7013
Epoch 7/100
10/10 [==============================] - 0s 2ms/step - loss: 0.7473 - accuracy: 0.7114
Epoch 8/100
10/10 [==============================] - 0s 2ms/step - loss: 0.7193 - accuracy: 0.7282
Epoch 9/100
10/10 [=========

In [96]:
best_model = ak_model.export_model()

In [97]:
best_model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 12)]              0         
_________________________________________________________________
multi_category_encoding (Mul (None, 12)                0         
_________________________________________________________________
normalization (Normalization (None, 12)                25        
_________________________________________________________________
dense (Dense)                (None, 256)               3328      
_________________________________________________________________
re_lu (ReLU)                 (None, 256)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               65792     
_________________________________________________________________
re_lu_1 (ReLU)               (None, 256)               0     

In [104]:
predictions = best_model.predict(pred_y)

In [113]:
predictions

array([[9.4976419e-01, 5.0194573e-02, 4.0870353e-05, 3.2379248e-07],
       [8.3065605e-01, 1.7058756e-02, 8.9664869e-03, 1.4331865e-01],
       [7.7247888e-01, 1.4256226e-01, 3.3818447e-04, 8.4620632e-02],
       [9.9976224e-01, 2.3778714e-04, 5.9246816e-09, 9.5355395e-09],
       [9.9976224e-01, 2.3778714e-04, 5.9246816e-09, 9.5355395e-09]],
      dtype=float32)

In [115]:
ca = []
for i in predictions:
    ca.append(list(i).index(max(i)))
ca

[0, 0, 0, 0, 0]

In [177]:
test.loc[test['ca']==4, 'ca'] = 0
test.loc[[41,46,80,81,96]]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
id                                                                        
41   52    1   2       138   223    0        1      169      0      0.0   
46   43    1   0       132   247    1        0      143      1      0.1   
80   58    1   1       125   220    0        1      144      0      0.4   
81   38    1   2       138   175    0        1      173      0      0.0   
96   38    1   2       138   175    0        1      173      0      0.0   

    slope  ca  thal  
id                   
41      2   0     2  
46      1   0     3  
80      1   0     3  
81      2   0     2  
96      2   0     2

In [6]:
train_thal = train

In [124]:
pred_y = train_thal[train_thal['thal']==0]
pred_y.pop('thal')
pred_y 

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
id                                                                         
130   53    0   2       128   216    0        0      115      0      0.0   

     slope  ca  target  
id                      
130      2   0       1

In [5]:
pred_y2 = train_thal[train_thal['thal']==1]
pred_y2.pop('thal')
pred_y2


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
id                                                                         
34    63    1   3       145   233    1        0      150      0      2.3   
44    66    1   0       160   228    0        0      138      0      2.3   
47    66    1   1       160   246    0        1      120      1      0.0   
61    57    1   0       110   201    0        1      126      1      1.5   
62    52    1   3       118   186    0        0      190      0      0.0   
86    44    1   0       120   169    0        1      144      1      2.8   
88    65    1   0       110   248    0        0      158      0      0.6   
118   59    1   0       164   176    1        0       90      0      1.0   

     slope  ca  target  
id                      
34       0   0       1  
44       2   0       1  
47       1   3       0  
61       1   0       1  
62       1   0       1  
86       0   0       0  
88       2   2       0  
118      1   2       0

In [144]:
train_thal = train_thal.drop([130])
train_thal

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
id                                                                         
1     53    1   2       130   197    1        0      152      0      1.2   
2     52    1   3       152   298    1        1      178      0      1.2   
3     54    1   1       192   283    0        0      195      0      0.0   
4     45    0   0       138   236    0        0      152      1      0.2   
5     35    1   1       122   192    0        1      174      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
147   50    1   2       140   233    0        1      163      0      0.6   
148   51    1   2        94   227    0        1      154      1      0.0   
149   69    1   3       160   234    1        0      131      0      0.1   
150   46    1   0       120   249    0        0      144      0      0.8   
151   63    0   1       140   195    0        1      179      0      0.0   

     slope  ca  thal  target  
id                            
1        0   0     2       1  
2        1   0     3       1  
3        2   1     3       0  
4        1   0     2       1  
5        2   0     2       1  
..     ...  ..   ...     ...  
147      1   1     3       0  
148      2   1     3       1  
149      1   1     2       1  
150      2   0     3       0  
151      2   2     2       1  

[150 rows x 14 columns]

In [7]:
train_thal2 = train_thal.drop([32,44,47,61,62,86,88,118])
train_thal2

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
id                                                                         
1     53    1   2       130   197    1        0      152      0      1.2   
2     52    1   3       152   298    1        1      178      0      1.2   
3     54    1   1       192   283    0        0      195      0      0.0   
4     45    0   0       138   236    0        0      152      1      0.2   
5     35    1   1       122   192    0        1      174      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
147   50    1   2       140   233    0        1      163      0      0.6   
148   51    1   2        94   227    0        1      154      1      0.0   
149   69    1   3       160   234    1        0      131      0      0.1   
150   46    1   0       120   249    0        0      144      0      0.8   
151   63    0   1       140   195    0        1      179      0      0.0   

     slope  ca  thal  target  
id                            
1        0   0     2       1  
2        1   0     3       1  
3        2   1     3       0  
4        1   0     2       1  
5        2   0     2       1  
..     ...  ..   ...     ...  
147      1   1     3       0  
148      2   1     3       1  
149      1   1     2       1  
150      2   0     3       0  
151      2   2     2       1  

[143 rows x 14 columns]

In [8]:
y_train_thal = train_thal.pop('thal')
y_train_thal = y_train_thal.to_numpy()
x_train_thal = train_thal.to_numpy()

In [ ]:
y_train_thal = train_thal2.pop('thal')
y_train_thal = y_train_thal.to_numpy()
x_train_thal = train_thal2.to_numpy()

In [146]:
y_train_thal

array([2, 3, 3, 2, 2, 3, 2, 2, 3, 2, 3, 3, 3, 3, 2, 2, 2, 2, 3, 2, 3, 2,
       3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 3, 2, 2, 3, 3, 2, 2, 3, 1,
       2, 2, 1, 2, 3, 2, 3, 2, 3, 2, 2, 2, 3, 2, 3, 3, 1, 1, 2, 2, 3, 3,
       3, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 3, 2, 3, 1, 3, 1,
       2, 2, 2, 2, 3, 2, 3, 2, 2, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3, 2,
       3, 3, 2, 2, 2, 2, 3, 1, 2, 3, 3, 2, 2, 3, 3, 3, 3, 3, 2, 3, 2, 2,
       2, 3, 3, 3, 2, 2, 2, 2, 3, 2, 2, 2, 3, 3, 3, 2, 3, 2], dtype=int64)

In [9]:
x_train_thal.shape

(143, 13)

In [11]:
import tensorflow as tf
import autokeras as ak

In [12]:
ak_model = ak.StructuredDataClassifier(
        overwrite=True, max_trials=5, 
        loss='categorical_crossentropy', seed=32
)
ak_model.fit(x_train_thal, y_train_thal, epochs=100, validation_split=0.3)

Trial 5 Complete [00h 00m 15s]
val_accuracy: 0.6000000238418579

Best val_accuracy So Far: 0.8666666746139526
Total elapsed time: 00h 00m 46s
INFO:tensorflow:Oracle triggered exit
Epoch 1/100
5/5 [==============================] - 0s 1ms/step - loss: 1.4466 - accuracy: 0.1049
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 1.1525 - accuracy: 0.6364
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9556 - accuracy: 0.7063
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8191 - accuracy: 0.7133
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.7217 - accuracy: 0.7273
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.6496 - accuracy: 0.7692
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5964 - accuracy: 0.7692
Epoch 8/100
5/5 [==============================] - 0s 1ms/step - loss: 0.5577 - accuracy: 0.7762
Epoch 9/100
5/5 [===========================

5/5 [==============================] - 0s 1ms/step - loss: 0.0254 - accuracy: 1.0000
Epoch 83/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0244 - accuracy: 1.0000
Epoch 84/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0235 - accuracy: 1.0000
Epoch 85/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0226 - accuracy: 1.0000
Epoch 86/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0218 - accuracy: 1.0000
Epoch 87/100
5/5 [==============================] - 0s 2ms/step - loss: 0.0210 - accuracy: 1.0000
Epoch 88/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0202 - accuracy: 1.0000
Epoch 89/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0195 - accuracy: 1.0000
Epoch 90/100
5/5 [==============================] - 0s 2ms/step - loss: 0.0188 - accuracy: 1.0000
Epoch 91/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0182 - accuracy: 1.0000
Epoch 92/100
5/5 [===============

In [13]:
best_model = ak_model.export_model()
pred_y = pred_y.to_numpy()
predictions = best_model.predict(pred_y)
predictions

NameError: name 'pred_y' is not defined

In [ ]:
train.loc[32,44,47,61,62,86,88,118,130]

In [152]:
train.loc[130]

age          53.0
sex           0.0
cp            2.0
trestbps    128.0
chol        216.0
fbs           0.0
restecg       0.0
thalach     115.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          0.0
target        1.0
Name: 130, dtype: float64

In [176]:
train.loc[[130],'thal'] = 1
train.loc[130]

age          53.0
sex           0.0
cp            2.0
trestbps    128.0
chol        216.0
fbs           0.0
restecg       0.0
thalach     115.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          1.0
target        1.0
Name: 130, dtype: float64

In [170]:
pred_y = test[test['thal'] == 0]
pred_y.pop('thal')
pred_y

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
id                                                                        
47   52    1   0       128   204    1        1      156      1      1.0   

    slope  ca  
id             
47      1   0

In [157]:
x_train_thal2 = test.drop([47])

In [163]:
x_train_thal = train.drop(columns = ['target'])
x_train_thal_all = pd.concat([x_train_thal, x_train_thal2])
y_train_thal_all = x_train_thal_all.pop('thal')

x_train_thal_all

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
id                                                                         
1     53    1   2       130   197    1        0      152      0      1.2   
2     52    1   3       152   298    1        1      178      0      1.2   
3     54    1   1       192   283    0        0      195      0      0.0   
4     45    0   0       138   236    0        0      152      1      0.2   
5     35    1   1       122   192    0        1      174      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
148   64    0   0       130   303    0        1      122      0      2.0   
149   43    0   0       132   341    1        0      136      1      3.0   
150   53    1   0       123   282    0        1       95      1      2.0   
151   67    0   2       152   277    0        1      172      0      0.0   
152   43    0   2       122   213    0        1      165      0      0.2   

     slope  ca  
id              
1        0   0  
2        1   0  
3        2   1  
4        1   0  
5        2   0  
..     ...  ..  
148      1   2  
149      1   0  
150      1   2  
151      2   1  
152      1   0  

[302 rows x 12 columns]

In [164]:
y_train_thal_all

id
1      2
2      3
3      3
4      2
5      2
      ..
148    2
149    3
150    3
151    2
152    2
Name: thal, Length: 302, dtype: int64

In [165]:
x_train_thal_all=x_train_thal_all.to_numpy()
y_train_thal_all=y_train_thal_all.to_numpy()


In [166]:
ak_model = ak.StructuredDataClassifier(
        overwrite=True, max_trials=5, 
        loss='categorical_crossentropy', seed=32
)
ak_model.fit(x_train_thal_all, y_train_thal_all, epochs=100, validation_split=0.3)

Trial 5 Complete [00h 00m 15s]
val_accuracy: 0.6410256624221802

Best val_accuracy So Far: 0.6794871687889099
Total elapsed time: 00h 00m 34s
INFO:tensorflow:Oracle triggered exit
Epoch 1/100
10/10 [==============================] - 0s 1ms/step - loss: 1.0544 - accuracy: 0.4272
Epoch 2/100
10/10 [==============================] - 0s 1ms/step - loss: 0.8046 - accuracy: 0.7020
Epoch 3/100
10/10 [==============================] - 0s 1ms/step - loss: 0.7088 - accuracy: 0.7053
Epoch 4/100
10/10 [==============================] - 0s 1ms/step - loss: 0.6690 - accuracy: 0.7119
Epoch 5/100
10/10 [==============================] - 0s 1ms/step - loss: 0.6450 - accuracy: 0.7152
Epoch 6/100
10/10 [==============================] - 0s 1ms/step - loss: 0.6247 - accuracy: 0.7417
Epoch 7/100
10/10 [==============================] - 0s 1ms/step - loss: 0.6072 - accuracy: 0.7417
Epoch 8/100
10/10 [==============================] - 0s 1ms/step - loss: 0.5913 - accuracy: 0.7483
Epoch 9/100
10/10 [=========

In [171]:
best_model = ak_model.export_model()
pred_y = pred_y.to_numpy()

predictions = best_model.predict(pred_y)
predictions

array([[2.7434858e-03, 7.9719658e-04, 9.9645931e-01]], dtype=float32)

In [173]:
max(predictions[0])

0.9964593

In [174]:
test.loc[test['thal'] == 0, 'thal'] = 2

categorical_features = ['sex', 'cp', 'slope', 'ca','exang', 'restecg', 'thal']
numeric_features = ['age', 'trestbps', 'thalach', 'fbs','oldpeak', 'chol']

In [182]:
train_ = train
y_train = train_.pop('target')
y_train = y_train.to_numpy()
x_train = train_.to_numpy()

pred_y = test.to_numpy()

In [186]:
y_train

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1],
      dtype=int64)

In [184]:
ak_model = ak.StructuredDataClassifier(
        overwrite=True, max_trials=10, 
        loss='binary_crossentropy', seed=32
)
ak_model.fit(x_train, y_train, epochs=100, validation_split=0.3)

Trial 10 Complete [00h 00m 04s]
val_accuracy: 0.8260869383811951

Best val_accuracy So Far: 0.9130434989929199
Total elapsed time: 00h 00m 51s
INFO:tensorflow:Oracle triggered exit
Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 0.6529 - accuracy: 0.7086
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5824 - accuracy: 0.7881
Epoch 3/100
5/5 [==============================] - 0s 1ms/step - loss: 0.5254 - accuracy: 0.8146
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4791 - accuracy: 0.8146
Epoch 5/100
5/5 [==============================] - 0s 1ms/step - loss: 0.4429 - accuracy: 0.8146
Epoch 6/100
5/5 [==============================] - 0s 1ms/step - loss: 0.4163 - accuracy: 0.8079
Epoch 7/100
5/5 [==============================] - 0s 1ms/step - loss: 0.3972 - accuracy: 0.8212
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3832 - accuracy: 0.8278
Epoch 9/100
5/5 [==========================

In [188]:
best_model = ak_model.export_model()
predictions = best_model.predict(pred_y)
predictions

array([[2.1398002e-06],
       [9.8649764e-01],
       [9.9998176e-01],
       [3.3050814e-08],
       [8.0455244e-01],
       [9.9686885e-01],
       [9.8812497e-01],
       [2.8678793e-09],
       [9.2626885e-07],
       [4.4635814e-01],
       [2.8870463e-01],
       [1.2334509e-06],
       [9.9997628e-01],
       [4.1187584e-02],
       [9.9994797e-01],
       [9.9996352e-01],
       [9.9999779e-01],
       [1.0708004e-02],
       [3.0026772e-06],
       [1.1008264e-05],
       [9.1870320e-01],
       [3.8692355e-03],
       [8.5307950e-01],
       [3.5674959e-02],
       [9.6574354e-01],
       [4.2875353e-01],
       [1.0000000e+00],
       [8.0457735e-01],
       [1.3933331e-02],
       [9.9983418e-01],
       [2.2545457e-04],
       [7.2440505e-04],
       [2.6052570e-05],
       [4.7122300e-02],
       [6.1670542e-01],
       [9.4430745e-03],
       [9.9820548e-01],
       [9.9976015e-01],
       [9.9994999e-01],
       [9.9291205e-01],
       [9.9989498e-01],
       [9.996202

In [189]:
train.to_csv('./_data/train_imputation.csv')
test.to_csv('./_data/test_imputation.csv')